[package]
name = "dff"
version = "0.2.0"
authors = ["Martin <martin.fontana08@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
structopt = { version = "0.3", default-features = false }
serde_any = "0.5.0"